
package de.uniluebeck.itm.ep0.poll.web;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Pollservice", targetNamespace = "www.itm.uniluebeck.de/pollservice", wsdlLocation = "http://localhost:8080/poll")
public class PollWebserviceClient
    extends Service
{

    private final static URL POLLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger
            .getLogger(de.uniluebeck.itm.ep0.poll.web.PollWebserviceClient.class
                    .getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = de.uniluebeck.itm.ep0.poll.web.PollWebserviceClient.class
                    .getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/poll");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/poll', retrying as a local file");
            logger.warning(e.getMessage());
        }
        POLLSERVICE_WSDL_LOCATION = url;
    }

    public PollWebserviceClient(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PollWebserviceClient() {
        super(POLLSERVICE_WSDL_LOCATION, new QName("www.itm.uniluebeck.de/pollservice", "Pollservice"));
    }

    /**
     * 
     * @return
     *     returns PollWebService
     */
    @WebEndpoint(name = "PollWebServicePort")
    public PollWebService getPollWebServicePort() {
        return super.getPort(new QName("www.itm.uniluebeck.de/pollservice",
                "PollWebServicePort"), PollWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PollWebService
     */
    @WebEndpoint(name = "PollWebServicePort")
    public PollWebService getPollWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("www.itm.uniluebeck.de/pollservice",
                "PollWebServicePort"), PollWebService.class, features);
    }

}
